version: "3"

services:

  jikan-rest:
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8889:80"
    networks:
      - jikan-rest
    #restart: always
    image: jikan-rest
    build:
      context: .
      dockerfile: Dockerfile

  redis:
    image: redis
    networks:
      - jikan-rest
    #restart: always

networks:
  jikan-rest:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.217.224/28
